In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy import optimize

In [2]:
data=pd.read_csv('train.csv')
test_data=pd.read_csv('test.csv')
data=data.to_numpy()
test_data=test_data.to_numpy()

In [3]:
X , Y = data[:,1:] ,data[:,0]
print(X.shape)
print(Y.shape)


(42000, 784)
(42000,)


In [4]:
np.dot( np.array([1,2,3,4,5]),np.transpose(np.array([1,1,1,1,1])) )

15

In [5]:
def sigmoid(z):
    return 1/(1+np.exp(-z))
def sigmoid_gradient(z):
    return np.multiply(sigmoid(z),1-sigmoid(z))

In [6]:
#NN consist of 3 layers input, hidden, output.
#lamda is regularization parameter.
def nnCostFunction(theta1,theta2,num_lable,X,Y,lamda):
    X_train=np.hstack((np.ones((X.shape[0],1)),X))
    A2=sigmoid(np.dot(X_train,np.transpose(Theta1)))
    A2=np.hstack((np.ones((A2.shape[0],1)),A2))
    A3=sigmoid(np.dot(A2,np.transpose(Theta2)))
    y_train=np.zeros((X.shape[0],num_lable))
    y_train[np.arange(X.shape[0]),Y-1]=1
    J=-np.multiply(y_train,np.log(A3))-np.multiply(1-y_train,np.log(1-A3))
    J=np.sum(J)/X.shape[0]
    regularization_term=( (np.sum(np.power(theta1[:,1:],2))+np.sum(np.power(theta2[:,1:],2))) * lam ) / (2*X.shape[0])
    J=J+regularization_term
    
    delta3=A3-y_train
    delta2=np.multiply(np.dot(delta3,theta2),np.multiply(A2,1-A2))
    theta1_grad=np.zeros(theta1.shape)
    theta2_grad=np.zeros(theta2.shape)
    for i in range(X.shape[0]):
        theta1_grad+=np.dot(delta2[i,1:][:,None],np.atleast_2d(X_train[i,:]))
        theta2_grad+=np.dot(delta3[i][:,None],np.atleast_2d(A2[i,:]))
    theta1_grad/=X.shape[0]
    theta2_grad/=X.shape[0]
    
    theta1_grad[:,1:]+=lamda*theta1[:,1:]/X.shape[0]
    theta2_grad[:,1:]+=lamda*theta2[:,1:]/X.shape[0]
    grad=np.hstack((theta1_grad.ravel(),theta2_grad.ravel()))
    return J, grad
    
    

In [19]:
def cost(theta1,theta2,num_lable,X,Y,lamda):
    X_train=np.hstack((np.ones((X.shape[0],1)),X))
    A2=sigmoid(np.dot(X_train,np.transpose(Theta1)))
    A2=np.hstack((np.ones((A2.shape[0],1)),A2))
    A3=sigmoid(np.dot(A2,np.transpose(Theta2)))
    y_train=np.zeros((X.shape[0],num_lable))
    y_train[np.arange(X.shape[0]),Y-1]=1
    J=-np.multiply(y_train,np.log(A3))-np.multiply(1-y_train,np.log(1-A3))
    J=np.sum(J)/X.shape[0]
    regularization_term=( (np.sum(np.power(theta1[:,1:],2))+np.sum(np.power(theta2[:,1:],2))) * lam ) / (2*X.shape[0])
    J=J+regularization_term
    return J

def gradient(theta1,theta2,num_lable,X,Y,lamda):
    X_train=np.hstack((np.ones((X.shape[0],1)),X))
    A2=sigmoid(np.dot(X_train,np.transpose(Theta1)))
    A2=np.hstack((np.ones((A2.shape[0],1)),A2))
    A3=sigmoid(np.dot(A2,np.transpose(Theta2)))
    y_train=np.zeros((X.shape[0],num_lable))
    y_train[np.arange(X.shape[0]),Y-1]=1
    
    delta3=A3-y_train
    delta2=np.multiply(np.dot(delta3,theta2),np.multiply(A2,1-A2))
    theta1_grad=np.zeros(theta1.shape)
    theta2_grad=np.zeros(theta2.shape)
    for i in range(X.shape[0]):
        theta1_grad+=np.dot(delta2[i,1:][:,None],np.atleast_2d(X_train[i,:]))
        theta2_grad+=np.dot(delta3[i][:,None],np.atleast_2d(A2[i,:]))
    theta1_grad/=X.shape[0]
    theta2_grad/=X.shape[0]
    
    theta1_grad[:,1:]+=lamda*theta1[:,1:]/X.shape[0]
    theta2_grad[:,1:]+=lamda*theta2[:,1:]/X.shape[0]
    grad=np.hstack((theta1_grad.ravel(),theta2_grad.ravel()))
    return grad
    

In [7]:
np.transpose(np.array([[1,1,1,1,1],[2,2,2,2,2]]))


array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

In [8]:
qq=np.array([[1],[2],[3],[4],[5]])
#np.transpose(qq)[0,1:][:,None]
ww=np.array([1,2,3,4,5])
ee=ww[:][:,None]
#print(ww[0,1:][:,None])
#print(ww)
#np.atleast_2d(ww)
#np.dot(np.atleast_2d(ww),qq)
ee.shape

(5, 1)

In [9]:
yy_train = np.zeros((X.shape[0], 10))
yy_train[np.arange(X.shape[0]), Y - 1] = 1
print(yy_train)
print(Y)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
[1 0 1 ... 7 6 9]


In [10]:
type(np.newaxis)

NoneType

In [20]:
'''
from scipy.io import loadmat
data = loadmat("ex4data1.mat")
X, y = data["X"], data["y"].ravel()
print(X.shape)
print(y.shape)
weight = loadmat("ex4weights.mat")
Theta1, Theta2 = weight["Theta1"], weight["Theta2"]
print(Theta1.shape)
print(Theta2.shape)
input_layer_size = 400
hidden_layer_size = 25
num_labels = 10
nn_params = np.hstack((Theta1.ravel(), Theta2.ravel()))
lam = 0
J= cost(Theta1, Theta2, num_labels, X, y, lam)
print(J)
'''

(5000, 400)
(5000,)
(25, 401)
(10, 26)
0.2876291651613189


In [12]:
X.shape

(42000, 784)

In [16]:
def random_weights(Lin,Lout):
    epsilon=0.12
    return np.random.RandomState(0).rand(Lout,Lin+1)*epsilon*2-epsilon

In [ ]:
input_layer = 784
hidden_layer = 30
output_layer = 10
initial_theta1=random_weights(input_layer,hidden_layer)
initial_theta2=random_weights(hidden_layer,output_layer)
lam=1
res=optimize.minimize(fun=cost, x0=nn_params,
                        args=(initial_theta1, initial_theta2, output_layer, X, Y, lam),
                        method='CG', jac=gradient, options={"maxiter": 50})